#!/usr/bin/env python3
from __future__ import annotations

import csv
import fcntl
import gzip
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterable, Iterator

import yaml

RUN_RE = re.compile(r"^(?:SRR|ERR|DRR)[0-9]{6,}$")


def deep_merge(a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]:
    out = dict(a)
    for k, v in b.items():
        if k in out and isinstance(out[k], dict) and isinstance(v, dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def _read_yaml(path: str | Path) -> dict[str, Any]:
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def load_config(species_config: str | Path, common_config: str | Path = "config/common.yaml") -> dict[str, Any]:
    """Load common, hardware profile, species, and optional runtime override.

    Merge order is deliberate: common < hardware profile < species < runtime.
    The runtime file affects performance only and is generated by autotuning.
    """
    common = _read_yaml(common_config)
    cfg = dict(common)
    profile_path = common.get("workflow", {}).get("resource_profile")
    if profile_path and Path(profile_path).exists():
        cfg = deep_merge(cfg, _read_yaml(profile_path))
    species = _read_yaml(species_config)
    cfg = deep_merge(cfg, species)
    runtime_path = os.environ.get(
        "WORKFLOW_RUNTIME_CONFIG",
        str(common.get("workflow", {}).get("runtime_config", "config/runtime.auto.yaml")),
    )
    if runtime_path and Path(runtime_path).exists():
        cfg = deep_merge(cfg, _read_yaml(runtime_path))
    cfg["_species_config"] = str(species_config)
    cfg["_common_config"] = str(common_config)
    cfg["_resource_profile"] = str(profile_path or "")
    cfg["_runtime_config"] = str(runtime_path or "")
    return cfg


def species_id(cfg: dict[str, Any]) -> str:
    return str(cfg["species"]["id"])


def workdir(cfg: dict[str, Any]) -> Path:
    return Path("work") / species_id(cfg)


def results_dir(cfg: dict[str, Any]) -> Path:
    return Path("results") / species_id(cfg)


def logdir(cfg: dict[str, Any]) -> Path:
    return Path("logs") / species_id(cfg)


def ensure_dirs(cfg: dict[str, Any]) -> None:
    for p in [
        workdir(cfg), results_dir(cfg), logdir(cfg),
        workdir(cfg) / "runs", workdir(cfg) / "references",
        results_dir(cfg) / "tables", results_dir(cfg) / "figures", results_dir(cfg) / "provenance",
        Path(cfg.get("resources", {}).get("lock_root", "work/.resource_locks")),
    ]:
        p.mkdir(parents=True, exist_ok=True)


def workflow_env(extra: dict[str, str] | None = None) -> dict[str, str]:
    """Prevent implicit BLAS/OpenMP oversubscription inside many workers."""
    env = os.environ.copy()
    env.update({
        "OMP_NUM_THREADS": "1",
        "OPENBLAS_NUM_THREADS": "1",
        "MKL_NUM_THREADS": "1",
        "NUMEXPR_NUM_THREADS": "1",
        "VECLIB_MAXIMUM_THREADS": "1",
        "MALLOC_ARENA_MAX": "4",
        "LC_ALL": env.get("LC_ALL", "C"),
    })
    if extra:
        env.update({str(k): str(v) for k, v in extra.items()})
    return env


def run_cmd(cmd: list[str] | str, *, log: Path | None = None, shell: bool = False,
            check: bool = True, env: dict[str, str] | None = None) -> subprocess.CompletedProcess:
    effective_env = workflow_env(env)
    if log:
        log.parent.mkdir(parents=True, exist_ok=True)
        with log.open("a", encoding="utf-8") as fh:
            fh.write("\n[CMD] " + (cmd if isinstance(cmd, str) else " ".join(map(str, cmd))) + "\n")
            fh.flush()
            return subprocess.run(cmd, shell=shell, check=check, stdout=fh,
                                  stderr=subprocess.STDOUT, text=True, env=effective_env)
    return subprocess.run(cmd, shell=shell, check=check, text=True, env=effective_env)


def run_cmd_retry(cmd: list[str] | str, *, attempts: int = 4, sleep_seconds: int = 20,
                  log: Path | None = None, shell: bool = False,
                  env: dict[str, str] | None = None) -> subprocess.CompletedProcess:
    last: Exception | None = None
    for attempt in range(1, attempts + 1):
        try:
            return run_cmd(cmd, log=log, shell=shell, check=True, env=env)
        except Exception as exc:
            last = exc
            if log:
                with log.open("a", encoding="utf-8") as fh:
                    fh.write(f"[WARN] command attempt {attempt}/{attempts} failed: {exc}\n")
            if attempt < attempts:
                time.sleep(sleep_seconds * attempt)
    assert last is not None
    raise last


def command_exists(name: str) -> bool:
    return shutil.which(name) is not None


def sha256(path: str | Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def open_text(path: str | Path, mode: str = "rt"):
    path = Path(path)
    return gzip.open(path, mode) if path.suffix == ".gz" else open(path, mode, encoding=None if "b" in mode else "utf-8")


def iter_fasta(path: str | Path):
    header: str | None = None
    seq: list[str] = []
    with open_text(path, "rt") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line.startswith(">"):
                if header is not None:
                    yield header, "".join(seq)
                header = line[1:]
                seq = []
            else:
                seq.append(line.strip())
        if header is not None:
            yield header, "".join(seq)


def write_fasta_record(fh, header: str, seq: str, width: int = 80) -> None:
    fh.write(">" + header + "\n")
    for i in range(0, len(seq), width):
        fh.write(seq[i : i + width] + "\n")


def read_qname_set(path: str | Path) -> set[str]:
    p = Path(path)
    if not p.exists() or p.stat().st_size == 0:
        return set()
    with open_text(p, "rt") as fh:
        return {line.strip() for line in fh if line.strip()}


def write_tsv(path: str | Path, rows: Iterable[dict[str, Any]], fieldnames: list[str] | None = None) -> None:
    rows = list(rows)
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        fieldnames = list(rows[0].keys()) if rows else []
    with p.open("w", newline="", encoding="utf-8") as fh:
        if not fieldnames:
            return
        w = csv.DictWriter(fh, fieldnames=fieldnames, delimiter="\t", extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)


def atomic_json(path: str | Path, obj: Any) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(json.dumps(obj, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(p)


def normalize_qname(name: str) -> str:
    token = name.strip().split()[0]
    if token.endswith("/1") or token.endswith("/2"):
        token = token[:-2]
    return token


def fail(msg: str, code: int = 1) -> None:
    print(f"[ERROR] {msg}", file=sys.stderr)
    raise SystemExit(code)




def scratch_dir(cfg: dict[str, Any], stage: str, run: str) -> Path:
    root = Path(str(cfg.get("resources", {}).get("tmp_root", "tmp")))
    p = root / species_id(cfg) / stage / run
    p.mkdir(parents=True, exist_ok=True)
    return p


def require_free_space(path: str | Path, minimum_gb: float) -> None:
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    free_gb = shutil.disk_usage(p).free / 1024**3
    if free_gb < float(minimum_gb):
        raise RuntimeError(
            f"insufficient temporary-disk space at {p}: {free_gb:.1f} GB free; "
            f"minimum configured={float(minimum_gb):.1f} GB"
        )

def resource_value(cfg: dict[str, Any], new_key: str, legacy_key: str | None = None,
                   default: Any | None = None) -> Any:
    r = cfg.get("resources", {})
    if new_key in r:
        return r[new_key]
    if legacy_key and legacy_key in r:
        return r[legacy_key]
    return default


def available_cpus() -> list[int]:
    try:
        return sorted(os.sched_getaffinity(0))
    except (AttributeError, OSError):
        return list(range(os.cpu_count() or 1))


def _physical_core_cpu_sets() -> list[list[int]]:
    allowed = set(available_cpus())
    try:
        p = subprocess.run(
            ["lscpu", "-p=CPU,CORE,SOCKET"], check=True, text=True,
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
        )
        core_map: dict[tuple[int, int], list[int]] = {}
        for line in p.stdout.splitlines():
            if not line or line.startswith("#"):
                continue
            cpu_s, core_s, socket_s = line.split(",")[:3]
            cpu = int(cpu_s)
            if cpu not in allowed:
                continue
            core_map.setdefault((int(socket_s), int(core_s)), []).append(cpu)
        if core_map:
            return [sorted(core_map[k]) for k in sorted(core_map)]
    except Exception:
        pass
    return [[c] for c in sorted(allowed)]


def cpu_groups(n_groups: int, strategy: str = "physical_core_blocks") -> list[list[int]]:
    cpus = available_cpus()
    n_groups = max(1, min(n_groups, len(cpus)))
    if strategy in {"physical_core_blocks", "core_blocks", "smt_siblings_together"}:
        cores = _physical_core_cpu_sets()
        n_groups = max(1, min(n_groups, len(cores)))
        groups: list[list[int]] = [[] for _ in range(n_groups)]
        base, extra = divmod(len(cores), n_groups)
        pos = 0
        for i in range(n_groups):
            width = base + (1 if i < extra else 0)
            groups[i] = sorted(cpu for core in cores[pos : pos + width] for cpu in core)
            pos += width
        return groups
    groups = [[] for _ in range(n_groups)]
    if strategy == "interleaved":
        for i, cpu in enumerate(cpus):
            groups[i % n_groups].append(cpu)
    else:
        base, extra = divmod(len(cpus), n_groups)
        pos = 0
        for i in range(n_groups):
            width = base + (1 if i < extra else 0)
            groups[i] = cpus[pos : pos + width]
            pos += width
    return groups


def taskset_prefix(cfg: dict[str, Any], slot: int, workers: int) -> list[str]:
    r = cfg.get("resources", {})
    if not r.get("cpu_affinity", False) or not command_exists("taskset"):
        return []
    groups = cpu_groups(workers, str(r.get("cpu_affinity_strategy", "physical_core_blocks")))
    group = groups[slot % len(groups)]
    return ["taskset", "-c", ",".join(map(str, group))] if group else []


def greedy_weighted_partitions(items: list[tuple[str, float]], n_parts: int) -> list[list[str]]:
    """Longest-processing-time greedy scheduling using spots as a stable proxy."""
    n_parts = max(1, n_parts)
    bins: list[list[str]] = [[] for _ in range(n_parts)]
    loads = [0.0] * n_parts
    for name, weight in sorted(items, key=lambda x: (-float(x[1]), x[0])):
        idx = min(range(n_parts), key=lambda i: loads[i])
        bins[idx].append(name)
        loads[idx] += max(float(weight), 1.0)
    return bins


@contextmanager
def file_slot(cfg: dict[str, Any], name: str, limit: int, poll_seconds: float = 0.25) -> Iterator[int]:
    """Cross-process counting semaphore implemented with flock lock files."""
    limit = max(1, int(limit))
    root = Path(cfg.get("resources", {}).get("lock_root", "work/.resource_locks")) / name
    root.mkdir(parents=True, exist_ok=True)
    handles: list[Any] = []
    try:
        while True:
            for i in range(limit):
                p = root / f"slot.{i}.lock"
                fh = p.open("a+")
                try:
                    fcntl.flock(fh.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
                    fh.seek(0)
                    fh.truncate(0)
                    fh.write(f"pid={os.getpid()} time={time.time()}\n")
                    fh.flush()
                    handles.append(fh)
                    yield i
                    return
                except BlockingIOError:
                    fh.close()
            time.sleep(poll_seconds)
    finally:
        for fh in handles:
            try:
                fcntl.flock(fh.fileno(), fcntl.LOCK_UN)
                fh.close()
            except Exception:
                pass


def local_read_resolution_path(cfg: dict[str, Any]) -> Path:
    return workdir(cfg) / "local_inputs" / "read_resolution.tsv"


def resolve_local_read_inputs(cfg: dict[str, Any], run: str, layout: str) -> dict[str, Any] | None:
    """Return the validated local FASTQ assignment for one run.

    The inventory is built once by workflow/local_inputs.py. Keeping lookup
    separate from filesystem scanning prevents every parallel worker from recursively
    traversing a multi-terabyte directory.
    """
    path = local_read_resolution_path(cfg)
    if not path.exists():
        return None
    with path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for row in reader:
            if row.get("Run") != run:
                continue
            if row.get("status") != "resolved":
                return None
            expected = layout.upper()
            observed = str(row.get("LibraryLayout", "")).upper()
            if observed and expected and observed != expected:
                raise RuntimeError(
                    f"local FASTQ inventory layout mismatch for {run}: manifest={expected}, inventory={observed}"
                )
            return dict(row)
    return None


def local_source_policy(cfg: dict[str, Any], kind: str) -> str:
    key = "read_source_policy" if kind == "reads" else "reference_source_policy"
    return str(cfg.get("local_inputs", {}).get(key, "prefer_local"))
